[package]
name = "sage-wasm"
version = "0.12.9"
edition = "2024"
license = "Apache-2.0"
description = "WebAssembly bindings for running the Sage wallet in a browser."
authors = ["Rigidity <me@rigidnetwork.com>"]
homepage = "https://github.com/rigidity/sage"
repository = "https://github.com/rigidity/sage"
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sage = { workspace = true }
sage-api = { workspace = true }
sage-config = { workspace = true }
sage-database = { workspace = true }
sage-keychain = { workspace = true }
sage-wallet = { workspace = true, features = ["coinset"] }

chia-protocol = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
tracing = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
